### ISSUE TITLE
下载的BIRD数据集下没有dev_tables.json和dev.json文件该怎么办？

### ISSUE THREAD

**Issue by XiaYifen** [quge2023/TA-SQL#1]
您好，我按照您给的网站下载了dev_databases数据集，但是解压后发现里面并没有dev_tables.json和dev.json文件，该怎么办呢？

**Comment by quge2023** [comment]
Thanks for your interest in our work. You could directly download the data from our leaderboard page. Here's the link: [https://bird-bench.github.io/](https://bird-bench.github.io/).
