### ISSUE TITLE
Seems the script is using a non-instantiated prompt in TASL module

### ISSUE THREAD

**Issue by imcsq** [quge2023/TA-SQL#2]
https://github.com/quge2023/TA-SQL/blob/5f616cce3c2916d35ffc7db61e46bdaf182455a5/src/modules.py#L133

`dummy_sql = collect_response(dummy_sql_prompt, stop = 'return SQL')`

seems supposed to be

`dummy_sql = collect_response(prompt, stop = 'return SQL')` ?

Context:
```python
prompt = dummy_sql_prompt.format(database_schema = database_schema, primary_key_dic = pk_dict, foreign_key_dic = fk_dict, question_prompt = q, evidence = evidence)
dummy_sql = collect_response(dummy_sql_prompt, stop = 'return SQL')
return prompt, dummy_sql
```

Not sure if the above-suggested modification is correct ;)

**Comment by quge2023** [comment]
You are right. Thanks for pointing that out.
